import Head from 'next/head';
import Script from 'next/script';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Layout({ children }: any) {
    return (
        <div>
            <Head>
                <title>Duplex Nulla</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                {/* <script src="/js/bulma-scripts.js"></script> */}
            </Head>
            <main className={` ${inter.className}`}>{children}</main>
            <Script src="/js/main-scripts.js"
                onLoad={(e) => {
                    console.log('Script load', e)
                }}
                onError={(e) => {
                    console.error('Script failed to load', e)
                }}
            />
        </div>
    );
}